# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'magiaa.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(682, 473)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(360, 10, 291, 181))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.btn_receitas_adicionar = QtWidgets.QPushButton(self.groupBox)
        self.btn_receitas_adicionar.setGeometry(QtCore.QRect(10, 40, 271, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_receitas_adicionar.sizePolicy().hasHeightForWidth())
        self.btn_receitas_adicionar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_receitas_adicionar.setFont(font)
        self.btn_receitas_adicionar.setObjectName("btn_receitas_adicionar")
        self.btn_receitas_gerenciar = QtWidgets.QPushButton(self.groupBox)
        self.btn_receitas_gerenciar.setGeometry(QtCore.QRect(10, 110, 271, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_receitas_gerenciar.sizePolicy().hasHeightForWidth())
        self.btn_receitas_gerenciar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_receitas_gerenciar.setFont(font)
        self.btn_receitas_gerenciar.setObjectName("btn_receitas_gerenciar")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 291, 181))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_ingredientes_adicionar = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_ingredientes_adicionar.setGeometry(QtCore.QRect(10, 40, 271, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ingredientes_adicionar.sizePolicy().hasHeightForWidth())
        self.btn_ingredientes_adicionar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_ingredientes_adicionar.setFont(font)
        self.btn_ingredientes_adicionar.setObjectName("btn_ingredientes_adicionar")
        self.btn_ingredientes_gerenciar = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_ingredientes_gerenciar.setGeometry(QtCore.QRect(10, 110, 271, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ingredientes_gerenciar.sizePolicy().hasHeightForWidth())
        self.btn_ingredientes_gerenciar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_ingredientes_gerenciar.setFont(font)
        self.btn_ingredientes_gerenciar.setObjectName("btn_ingredientes_gerenciar")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 230, 291, 181))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.btn_fabricacoes_adicionar = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_fabricacoes_adicionar.setGeometry(QtCore.QRect(10, 40, 271, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_fabricacoes_adicionar.sizePolicy().hasHeightForWidth())
        self.btn_fabricacoes_adicionar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_fabricacoes_adicionar.setFont(font)
        self.btn_fabricacoes_adicionar.setObjectName("btn_fabricacoes_adicionar")
        self.btn_fabricacoes_gerenciar = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_fabricacoes_gerenciar.setGeometry(QtCore.QRect(10, 110, 271, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_fabricacoes_gerenciar.sizePolicy().hasHeightForWidth())
        self.btn_fabricacoes_gerenciar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_fabricacoes_gerenciar.setFont(font)
        self.btn_fabricacoes_gerenciar.setObjectName("btn_fabricacoes_gerenciar")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(360, 230, 291, 181))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.btn_vendas_adicionar = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_vendas_adicionar.setGeometry(QtCore.QRect(10, 40, 271, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_vendas_adicionar.sizePolicy().hasHeightForWidth())
        self.btn_vendas_adicionar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_vendas_adicionar.setFont(font)
        self.btn_vendas_adicionar.setObjectName("btn_vendas_adicionar")
        self.btn_vendas_gerenciar = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_vendas_gerenciar.setGeometry(QtCore.QRect(10, 110, 271, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_vendas_gerenciar.sizePolicy().hasHeightForWidth())
        self.btn_vendas_gerenciar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_vendas_gerenciar.setFont(font)
        self.btn_vendas_gerenciar.setObjectName("btn_vendas_gerenciar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 682, 21))
        self.menubar.setObjectName("menubar")
        self.menuIngredientes = QtWidgets.QMenu(self.menubar)
        self.menuIngredientes.setObjectName("menuIngredientes")
        self.menuReceitas = QtWidgets.QMenu(self.menubar)
        self.menuReceitas.setObjectName("menuReceitas")
        self.menuFabrica_es = QtWidgets.QMenu(self.menubar)
        self.menuFabrica_es.setObjectName("menuFabrica_es")
        self.menuVendas = QtWidgets.QMenu(self.menubar)
        self.menuVendas.setObjectName("menuVendas")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdicionar = QtWidgets.QAction(MainWindow)
        self.actionAdicionar.setObjectName("actionAdicionar")
        self.actionGerenciar = QtWidgets.QAction(MainWindow)
        self.actionGerenciar.setObjectName("actionGerenciar")
        self.actionAdicionar_2 = QtWidgets.QAction(MainWindow)
        self.actionAdicionar_2.setObjectName("actionAdicionar_2")
        self.actionAdicionar_3 = QtWidgets.QAction(MainWindow)
        self.actionAdicionar_3.setObjectName("actionAdicionar_3")
        self.actionAdicionar_4 = QtWidgets.QAction(MainWindow)
        self.actionAdicionar_4.setObjectName("actionAdicionar_4")
        self.actionGerenciar_2 = QtWidgets.QAction(MainWindow)
        self.actionGerenciar_2.setObjectName("actionGerenciar_2")
        self.actionGerenciar_3 = QtWidgets.QAction(MainWindow)
        self.actionGerenciar_3.setObjectName("actionGerenciar_3")
        self.menuIngredientes.addAction(self.actionAdicionar)
        self.menuIngredientes.addAction(self.actionGerenciar)
        self.menuReceitas.addSeparator()
        self.menuReceitas.addAction(self.actionAdicionar_2)
        self.menuReceitas.addAction(self.actionGerenciar_2)
        self.menuFabrica_es.addAction(self.actionAdicionar_3)
        self.menuFabrica_es.addAction(self.actionGerenciar_3)
        self.menuVendas.addAction(self.actionAdicionar_4)
        self.menubar.addAction(self.menuIngredientes.menuAction())
        self.menubar.addAction(self.menuReceitas.menuAction())
        self.menubar.addAction(self.menuFabrica_es.menuAction())
        self.menubar.addAction(self.menuVendas.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Receitas"))
        self.btn_receitas_adicionar.setText(_translate("MainWindow", "Adicionar"))
        self.btn_receitas_gerenciar.setText(_translate("MainWindow", "Gerenciar"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Ingredientes"))
        self.btn_ingredientes_adicionar.setText(_translate("MainWindow", "Adicionar"))
        self.btn_ingredientes_gerenciar.setText(_translate("MainWindow", "Gerenciar"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Fabricações"))
        self.btn_fabricacoes_adicionar.setText(_translate("MainWindow", "Adicionar"))
        self.btn_fabricacoes_gerenciar.setText(_translate("MainWindow", "Gerenciar"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Vendas"))
        self.btn_vendas_adicionar.setText(_translate("MainWindow", "Adicionar"))
        self.btn_vendas_gerenciar.setText(_translate("MainWindow", "Gerenciar"))
        self.menuIngredientes.setTitle(_translate("MainWindow", "Ingredientes"))
        self.menuReceitas.setTitle(_translate("MainWindow", "Receitas"))
        self.menuFabrica_es.setTitle(_translate("MainWindow", "Fabricações"))
        self.menuVendas.setTitle(_translate("MainWindow", "Vendas"))
        self.actionAdicionar.setText(_translate("MainWindow", "Adicionar"))
        self.actionGerenciar.setText(_translate("MainWindow", "Gerenciar"))
        self.actionAdicionar_2.setText(_translate("MainWindow", "Adicionar"))
        self.actionAdicionar_3.setText(_translate("MainWindow", "Adicionar"))
        self.actionAdicionar_4.setText(_translate("MainWindow", "Adicionar"))
        self.actionGerenciar_2.setText(_translate("MainWindow", "Gerenciar"))
        self.actionGerenciar_3.setText(_translate("MainWindow", "Gerenciar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())